/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/NissanZ.glb 
*/

import React, { useRef } from 'react'
import { useSnapshot } from "valtio"

import { useGLTF } from '@react-three/drei'
import { useCustomization } from '../context/Customization';
import { state } from '../components/ColorPicker';


export function NissanZ(props) {
  const { nodes, materials } = useGLTF('models/NissanZ.glb')
  const { overlay } = useCustomization()
  const snap1 = useSnapshot(state)

  const canvasRef = useRef(document.createElement("canvas"));
  const textureRef = useRef();
  const context = useRef(canvasRef.current.getContext("2d"));
console.log()

  canvasRef.current.width = 1600;
  canvasRef.current.height = 1600;

  let ctx = context.current;

  ctx.globalCompositeOperation = "hue";

  const img = document.getElementById(`overlay${overlay}`);

  if (img.complete) {
    ctx.drawImage(img, 0, 0);
    if (snap1.base.BaseMtl !== "none") {
      if(overlay!==1){
      ctx.fillStyle = snap1.base.BaseMtl;
      ctx.fillRect(0, 0, 1600, 1600);
      }
    }


    if (textureRef.current) {
      textureRef.current.needsUpdate = true;
    }
  }

  else {
    img.onload = function () {
      ctx.drawImage(img, 0, 0);
      if (snap1.base.BaseMtl !== "none") {
        if(overlay!==1){
        ctx.fillStyle = snap1.base.BaseMtl;
        ctx.fillRect(0, 0, 1600, 1600);
        }
      }
      


      if (textureRef.current) {
        textureRef.current.needsUpdate = true;
      }
    }
  }
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_22.geometry} material={materials.material_8} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.material_9} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.material_10} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.material_10} />
      <mesh geometry={nodes.Object_30.geometry} material={materials.material_11} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.material_12} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Body.geometry}>
        <meshStandardMaterial {...materials.BaseMtl} color={overlay==1 || overlay==13 ? (snap1.base.BaseMtl!=="none" ? snap1.base.BaseMtl : 0xffffff) : 0xffffff}>
          <canvasTexture
            flipY={false}
            wrapS={1000}
            wrapT={1000}
            colorSpace='srgb'
            ref={textureRef}
            attach="map"
            image={canvasRef.current}
          />
        </meshStandardMaterial>
      </mesh>
      <mesh geometry={nodes.Object_10.geometry} material={materials.material_2} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.material_3} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.material_4} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.material_5} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.material_6} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.material_7} />
    </group>
  )
}

useGLTF.preload('/NissanZ.glb')
